mex -v -compatibleArrayDims -O ...
    -I"ReflexxesTypeII\include" sfun_trajgen_pos.cpp ...
    ReflexxesTypeII\src\TypeIIRML\ReflexxesAPI.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLCalculatePositionalExtrems.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisions.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree1A.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree1B.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree1C.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree2.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLFallBackStrategy.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLIsPhaseSynchronizationPossible.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLPolynomial.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLPosition.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLQuicksort.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLSetupModifiedSelectionVector.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep1.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep1IntermediateProfiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep1Profiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2IntermediateProfiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2PhaseSynchronization.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2Profiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2WithoutSynchronization.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep3.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocity.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityCalculatePositionalExtrems.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityFallBackStrategy.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityIsPhaseSynchronizationPossible.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityMethods.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocitySetupPhaseSyncSelectionVector.cpp

mex -v -compatibleArrayDims -O ...
    -I"ReflexxesTypeII\include" sfun_trajgen_vel.cpp ...
    ReflexxesTypeII\src\TypeIIRML\ReflexxesAPI.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLCalculatePositionalExtrems.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisions.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree1A.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree1B.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree1C.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLDecisionTree2.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLFallBackStrategy.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLIsPhaseSynchronizationPossible.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLPolynomial.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLPosition.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLQuicksort.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLSetupModifiedSelectionVector.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep1.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep1IntermediateProfiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep1Profiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2IntermediateProfiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2PhaseSynchronization.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2Profiles.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep2WithoutSynchronization.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLStep3.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocity.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityCalculatePositionalExtrems.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityFallBackStrategy.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityIsPhaseSynchronizationPossible.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocityMethods.cpp ...
    ReflexxesTypeII\src\TypeIIRML\TypeIIRMLVelocitySetupPhaseSyncSelectionVector.cpp